# Generated by Django 4.1.7 on 2023-06-18 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectsDisplay', '0003_alter_project_technology'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='breif_description',
            field=models.CharField(default='breif description here...', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='technology',
            field=models.CharField(max_length=75),
        ),
    ]
