# Generated by Django 4.1.7 on 2023-06-25 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectsDisplay', '0009_alter_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='github_link',
            field=models.URLField(default=None),
        ),
    ]
