# Generated by Django 4.1.7 on 2023-06-18 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categories',
            field=models.ManyToManyField(default='NA', related_name='posts', to='Blog.category'),
        ),
    ]
