# Generated by Django 4.1.7 on 2023-06-28 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_alter_post_categories'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
