# Generated by Django 4.1.7 on 2023-03-22 20:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_entry_mod_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='mod_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 22, 20, 50, 24, 303656, tzinfo=datetime.timezone.utc)),
        ),
    ]
