# Generated by Django 4.1.7 on 2023-03-22 21:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_entry_mod_date_alter_entry_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='number_of_comments',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='entry',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 22, 21, 13, 26, 346220, tzinfo=datetime.timezone.utc)),
        ),
    ]
