# Generated by Django 4.1.7 on 2023-03-22 21:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_entry_number_of_comments_alter_entry_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='pub_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 3, 22, 21, 14, 26, 214904, tzinfo=datetime.timezone.utc)),
        ),
    ]
