# Generated by Django 4.1.7 on 2023-03-22 21:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_entry_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='author',
            field=models.CharField(default='Andrew Root', max_length=30),
        ),
        migrations.AlterField(
            model_name='entry',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 22, 21, 19, 34, 424616, tzinfo=datetime.timezone.utc)),
        ),
    ]
