# Generated by Django 4.1.7 on 2023-03-22 21:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_entry_author_alter_entry_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 22, 21, 28, 56, 707250, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='entry',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
