# Generated by Django 4.1.7 on 2023-03-22 21:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_entry_pub_date_alter_entry_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 22, 21, 31, 14, 186864, tzinfo=datetime.timezone.utc)),
        ),
    ]
