# Generated by Django 4.1.7 on 2023-06-20 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=12)),
                ('body', models.TextField()),
                ('prof_pic', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
