# Generated by Django 4.1.7 on 2023-06-25 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bio',
            name='linkedIn_link',
            field=models.URLField(default=None),
        ),
    ]
