# Generated by Django 4.1.7 on 2023-06-25 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bio', '0002_bio_linkedin_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='bio',
            name='github_link',
            field=models.URLField(default=None),
        ),
    ]
